# Generated by Django 5.0.8 on 2025-12-15 09:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Montant de l'investissement en FCFA", max_digits=15, validators=[django.core.validators.MinValueValidator(1000)])),
                ('message', models.TextField(blank=True, help_text='Message optionnel pour le porteur de projet')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('card', 'Carte bancaire'), ('cash', 'Espèces')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Complété'), ('failed', 'Échec'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'db_table': 'investments_investment',
                'ordering': ['-invested_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1000)])),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('is_limited', models.BooleanField(default=False)),
                ('quantity_available', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_claimed', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='projects.project')),
            ],
            options={
                'verbose_name': "Récompense d'investissement",
                'verbose_name_plural': "Récompenses d'investissement",
                'db_table': 'investments_investmentreward',
                'ordering': ['minimum_amount'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentRewardChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_choice', to='investments.investment')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by', to='investments.investmentreward')),
            ],
            options={
                'verbose_name': 'Choix de récompense',
                'verbose_name_plural': 'Choix de récompenses',
                'db_table': 'investments_investmentrewardchoice',
            },
        ),
    ]
