# Generated by Django 5.0.8 on 2025-12-15 09:30

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='Objectif de financement en FCFA', max_digits=15, validators=[django.core.validators.MinValueValidator(100000)])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant actuellement levé en FCFA', max_digits=15)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('country', models.CharField(choices=[('CM', 'Cm'), ('SN', 'Sn'), ('CI', 'Ci'), ('BJ', 'Bj'), ('TG', 'Tg'), ('BF', 'Bf'), ('ML', 'Ml'), ('NE', 'Ne'), ('GN', 'Gn'), ('CD', 'Cd'), ('CG', 'Cg'), ('GA', 'Ga'), ('TD', 'Td'), ('CF', 'Cf'), ('RW', 'Rw'), ('BI', 'Bi'), ('KE', 'Ke'), ('TZ', 'Tz'), ('UG', 'Ug'), ('NG', 'Ng'), ('GH', 'Gh'), ('MG', 'Mg'), ('MU', 'Mu')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('active', 'Actif'), ('successful', 'Financé avec succès'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/featured/')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube ou Vimeo')),
                ('budget_breakdown', models.JSONField(default=dict, help_text='Répartition détaillée du budget')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='categories.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'projects_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.projectcomment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'db_table': 'projects_projectcomment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Image de projet',
                'verbose_name_plural': 'Images de projets',
                'db_table': 'projects_projectimage',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
            options={
                'verbose_name': 'Mise à jour de projet',
                'verbose_name_plural': 'Mises à jour de projets',
                'db_table': 'projects_projectupdate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet sauvegardé',
                'verbose_name_plural': 'Projets sauvegardés',
                'db_table': 'projects_savedproject',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
