# Generated by Django 5.0.8 on 2025-12-15 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_investment', models.BooleanField(default=True)),
                ('email_investment_completed', models.BooleanField(default=True)),
                ('email_project_updates', models.BooleanField(default=True)),
                ('email_new_messages', models.BooleanField(default=True)),
                ('email_project_deadline', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('push_new_investment', models.BooleanField(default=True)),
                ('push_investment_completed', models.BooleanField(default=True)),
                ('push_project_updates', models.BooleanField(default=False)),
                ('push_new_messages', models.BooleanField(default=True)),
                ('push_project_deadline', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_new_investment', models.BooleanField(default=False)),
                ('sms_investment_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
                'db_table': 'notifications_notificationpreference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_investment', 'Nouvel investissement reçu'), ('investment_completed', 'Investissement confirmé'), ('project_approved', 'Projet approuvé'), ('project_rejected', 'Projet rejeté'), ('project_funded', 'Projet financé avec succès'), ('project_failed', 'Projet non financé'), ('new_message', 'Nouveau message'), ('project_update', 'Mise à jour de projet'), ('new_comment', 'Nouveau commentaire'), ('project_deadline', 'Fin de campagne approche'), ('welcome', 'Bienvenue'), ('system', 'Notification système')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='investments.investment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
